[3/14/2023, 12:13:22 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 12:13:23 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 12:13:23 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 12:13:29 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:13:29 AM] [SERVER] [error]: uncaughtException: existEmail
Error: existEmail
    at signUp (/home/node/app/dist/server.js:111:43335)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
{"date":"Mon Mar 13 2023 17:13:29 GMT+0000 (Coordinated Universal Time)","error":{"type":"BadRequestError"},"exception":true,"level":"error","message":"uncaughtException: existEmail\nError: existEmail\n    at signUp (/home/node/app/dist/server.js:111:43335)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","os":{"loadavg":[1.21,1.39,1.46],"uptime":10897.15},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17899195,"external":18817804,"heapTotal":28401664,"heapUsed":22345576,"rss":83386368},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error: existEmail\n    at signUp (/home/node/app/dist/server.js:111:43335)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","trace":[{"column":43335,"file":"/home/node/app/dist/server.js","function":"signUp","line":111,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false}]}
[3/14/2023, 12:18:40 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 12:19:07 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 12:19:08 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 12:19:08 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 12:19:12 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:19:12 AM] [SERVER] [error]: [App] ERROR:: "existEmail"
[3/14/2023, 12:19:12 AM] [SERVER] [info]: err -> Error: existEmail
[3/14/2023, 12:19:12 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 12:19:12 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: email_1 dup key: { email: "hcaiooo@ckhansu.com" }
[3/14/2023, 12:19:12 AM] [SERVER] [error]: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at ir.set.ir.header (/home/node/app/dist/server.js:99:13390)
    at ir.send (/home/node/app/dist/server.js:99:8913)
    at ir.json (/home/node/app/dist/server.js:99:10045)
    at signUp (/home/node/app/dist/server.js:111:43620)
{"date":"Mon Mar 13 2023 17:19:12 GMT+0000 (Coordinated Universal Time)","error":{"code":"ERR_HTTP_HEADERS_SENT"},"exception":true,"level":"error","message":"uncaughtException: Cannot set headers after they are sent to the client\nError [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ir.set.ir.header (/home/node/app/dist/server.js:99:13390)\n    at ir.send (/home/node/app/dist/server.js:99:8913)\n    at ir.json (/home/node/app/dist/server.js:99:10045)\n    at signUp (/home/node/app/dist/server.js:111:43620)","os":{"loadavg":[1.41,1.17,1.3],"uptime":11239.72},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17875039,"external":18795696,"heapTotal":38363136,"heapUsed":21246840,"rss":85356544},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ir.set.ir.header (/home/node/app/dist/server.js:99:13390)\n    at ir.send (/home/node/app/dist/server.js:99:8913)\n    at ir.json (/home/node/app/dist/server.js:99:10045)\n    at signUp (/home/node/app/dist/server.js:111:43620)","trace":[{"column":5,"file":"node:internal/errors","function":"new NodeError","line":399,"method":null,"native":false},{"column":11,"file":"node:_http_outgoing","function":"ServerResponse.setHeader","line":663,"method":"setHeader","native":false},{"column":13390,"file":"/home/node/app/dist/server.js","function":"ir.set.ir.header","line":99,"method":"header","native":false},{"column":8913,"file":"/home/node/app/dist/server.js","function":"ir.send","line":99,"method":"send","native":false},{"column":10045,"file":"/home/node/app/dist/server.js","function":"ir.json","line":99,"method":"json","native":false},{"column":43620,"file":"/home/node/app/dist/server.js","function":"signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 12:20:43 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 12:21:09 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 12:21:10 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 12:21:11 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 12:21:17 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:21:17 AM] [SERVER] [error]: [App] ERROR:: "existEmail"
[3/14/2023, 12:21:17 AM] [SERVER] [info]: err -> Error: existEmail
[3/14/2023, 12:21:17 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 12:21:17 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: email_1 dup key: { email: "hcaiooo@ckhansu.com" }
[3/14/2023, 12:21:17 AM] [SERVER] [error]: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at ir.set.ir.header (/home/node/app/dist/server.js:99:13390)
    at ir.send (/home/node/app/dist/server.js:99:8913)
    at ir.json (/home/node/app/dist/server.js:99:10045)
    at signUp (/home/node/app/dist/server.js:111:43629)
{"date":"Mon Mar 13 2023 17:21:17 GMT+0000 (Coordinated Universal Time)","error":{"code":"ERR_HTTP_HEADERS_SENT"},"exception":true,"level":"error","message":"uncaughtException: Cannot set headers after they are sent to the client\nError [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ir.set.ir.header (/home/node/app/dist/server.js:99:13390)\n    at ir.send (/home/node/app/dist/server.js:99:8913)\n    at ir.json (/home/node/app/dist/server.js:99:10045)\n    at signUp (/home/node/app/dist/server.js:111:43629)","os":{"loadavg":[2.1,1.44,1.38],"uptime":11364.98},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17914323,"external":18834980,"heapTotal":28663808,"heapUsed":23808184,"rss":85053440},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ir.set.ir.header (/home/node/app/dist/server.js:99:13390)\n    at ir.send (/home/node/app/dist/server.js:99:8913)\n    at ir.json (/home/node/app/dist/server.js:99:10045)\n    at signUp (/home/node/app/dist/server.js:111:43629)","trace":[{"column":5,"file":"node:internal/errors","function":"new NodeError","line":399,"method":null,"native":false},{"column":11,"file":"node:_http_outgoing","function":"ServerResponse.setHeader","line":663,"method":"setHeader","native":false},{"column":13390,"file":"/home/node/app/dist/server.js","function":"ir.set.ir.header","line":99,"method":"header","native":false},{"column":8913,"file":"/home/node/app/dist/server.js","function":"ir.send","line":99,"method":"send","native":false},{"column":10045,"file":"/home/node/app/dist/server.js","function":"ir.json","line":99,"method":"json","native":false},{"column":43629,"file":"/home/node/app/dist/server.js","function":"signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 12:21:28 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:21:28 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 12:26:45 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 12:31:25 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 12:31:26 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 12:31:37 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 12:31:41 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:31:41 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 12:31:41 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
[3/14/2023, 12:36:25 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 12:36:59 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 12:37:00 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 12:37:00 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 12:37:07 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:37:07 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 12:37:07 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
{"date":"Mon Mar 13 2023 17:37:07 GMT+0000 (Coordinated Universal Time)","error":{"type":"BadRequestError"},"exception":true,"level":"error","message":"uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\nError: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.frt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43676)","os":{"loadavg":[1.5,1.63,1.57],"uptime":12315.35},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17904495,"external":18825152,"heapTotal":28663808,"heapUsed":23621104,"rss":86269952},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.frt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43676)","trace":[{"column":42880,"file":"/home/node/app/dist/server.js","function":"Object.frt [as createNewUser]","line":111,"method":"frt [as createNewUser]","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":43676,"file":"/home/node/app/dist/server.js","function":"async signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 12:37:07 AM] [SERVER] [error]: uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
    at Object.frt [as createNewUser] (/home/node/app/dist/server.js:111:42880)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async signUp (/home/node/app/dist/server.js:111:43676)
[3/14/2023, 12:40:21 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 12:40:52 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 12:40:53 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 12:40:53 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 12:41:23 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:41:24 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 12:41:24 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
{"date":"Mon Mar 13 2023 17:41:24 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\nError: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43678)","os":{"loadavg":[1.76,1.5,1.51],"uptime":12571.47},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17889657,"external":18808231,"heapTotal":21061632,"heapUsed":19476952,"rss":78036992},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43678)","trace":[{"column":42880,"file":"/home/node/app/dist/server.js","function":"Object.lrt [as createNewUser]","line":111,"method":"lrt [as createNewUser]","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":43678,"file":"/home/node/app/dist/server.js","function":"async signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 12:41:24 AM] [SERVER] [error]: uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async signUp (/home/node/app/dist/server.js:111:43678)
[3/14/2023, 12:46:36 AM] [SERVER] [info]: [object Object]
[3/14/2023, 12:46:36 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 12:46:36 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
{"date":"Mon Mar 13 2023 17:46:36 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\nError: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43678)","os":{"loadavg":[0.92,1.33,1.45],"uptime":12884.18},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17898989,"external":18817603,"heapTotal":21848064,"heapUsed":20220768,"rss":78815232},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43678)","trace":[{"column":42880,"file":"/home/node/app/dist/server.js","function":"Object.lrt [as createNewUser]","line":111,"method":"lrt [as createNewUser]","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":43678,"file":"/home/node/app/dist/server.js","function":"async signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 12:46:36 AM] [SERVER] [error]: uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async signUp (/home/node/app/dist/server.js:111:43678)
[3/14/2023, 12:50:08 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 1:06:54 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 1:06:55 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 1:06:56 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 1:07:00 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 1:09:00 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 1:09:00 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 1:09:01 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 1:09:06 AM] [SERVER] [info]: [object Object]
[3/14/2023, 1:09:06 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 1:09:06 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
{"date":"Mon Mar 13 2023 18:09:06 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\nError: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43678)","os":{"loadavg":[1.91,1.23,0.68],"uptime":560.3},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17864822,"external":18785479,"heapTotal":22634496,"heapUsed":21134384,"rss":78426112},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:43678)","trace":[{"column":42880,"file":"/home/node/app/dist/server.js","function":"Object.lrt [as createNewUser]","line":111,"method":"lrt [as createNewUser]","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":43678,"file":"/home/node/app/dist/server.js","function":"async signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 1:09:06 AM] [SERVER] [error]: uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
    at Object.lrt [as createNewUser] (/home/node/app/dist/server.js:111:42880)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async signUp (/home/node/app/dist/server.js:111:43678)
[3/14/2023, 1:25:25 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 1:27:09 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 1:27:10 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 1:27:10 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 1:31:28 AM] [SERVER] [info]: [object Object]
[3/14/2023, 1:31:29 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 1:31:29 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
{"date":"Mon Mar 13 2023 18:31:29 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\nError: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.cnt [as createNewUser] (/home/node/app/dist/server.js:111:44126)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:44934)","os":{"loadavg":[2.11,1.95,1.41],"uptime":1903.1},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17896710,"external":18815284,"heapTotal":21856256,"heapUsed":19886768,"rss":73224192},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.cnt [as createNewUser] (/home/node/app/dist/server.js:111:44126)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:44934)","trace":[{"column":44126,"file":"/home/node/app/dist/server.js","function":"Object.cnt [as createNewUser]","line":111,"method":"cnt [as createNewUser]","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":44934,"file":"/home/node/app/dist/server.js","function":"async signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 1:31:29 AM] [SERVER] [error]: uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
    at Object.cnt [as createNewUser] (/home/node/app/dist/server.js:111:44126)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async signUp (/home/node/app/dist/server.js:111:44934)
[3/14/2023, 1:33:09 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 1:34:50 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 1:34:51 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 1:34:51 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 1:35:20 AM] [SERVER] [info]: [object Object]
{"date":"Mon Mar 13 2023 18:35:20 GMT+0000 (Coordinated Universal Time)","error":{"name":"BadRequestError","status":400},"exception":true,"level":"error","message":"uncaughtException: create new user fail.\nBadRequestError: create new user fail.\n    at signUp (/home/node/app/dist/server.js:111:44704)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at PM.exports.validateRegisterInput (/home/node/app/dist/server.js:114:157112)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at Am.dispatch (/home/node/app/dist/server.js:88:5663)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at /home/node/app/dist/server.js:88:8574\n    at Kp.process_params (/home/node/app/dist/server.js:88:9118)","os":{"loadavg":[2.07,2.15,1.63],"uptime":2134.18},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17882864,"external":18799390,"heapTotal":21069824,"heapUsed":19080888,"rss":75993088},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"BadRequestError: create new user fail.\n    at signUp (/home/node/app/dist/server.js:111:44704)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at PM.exports.validateRegisterInput (/home/node/app/dist/server.js:114:157112)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at Am.dispatch (/home/node/app/dist/server.js:88:5663)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at /home/node/app/dist/server.js:88:8574\n    at Kp.process_params (/home/node/app/dist/server.js:88:9118)","trace":[{"column":44704,"file":"/home/node/app/dist/server.js","function":"signUp","line":111,"method":null,"native":false},{"column":3816,"file":"/home/node/app/dist/server.js","function":"wm.handle_request","line":88,"method":"handle_request","native":false},{"column":5864,"file":"/home/node/app/dist/server.js","function":"u","line":88,"method":null,"native":false},{"column":157112,"file":"/home/node/app/dist/server.js","function":"PM.exports.validateRegisterInput","line":114,"method":"validateRegisterInput","native":false},{"column":3816,"file":"/home/node/app/dist/server.js","function":"wm.handle_request","line":88,"method":"handle_request","native":false},{"column":5864,"file":"/home/node/app/dist/server.js","function":"u","line":88,"method":null,"native":false},{"column":5663,"file":"/home/node/app/dist/server.js","function":"Am.dispatch","line":88,"method":"dispatch","native":false},{"column":3816,"file":"/home/node/app/dist/server.js","function":"wm.handle_request","line":88,"method":"handle_request","native":false},{"column":8574,"file":"/home/node/app/dist/server.js","function":null,"line":88,"method":null,"native":false},{"column":9118,"file":"/home/node/app/dist/server.js","function":"Kp.process_params","line":88,"method":"process_params","native":false}]}
[3/14/2023, 1:35:20 AM] [SERVER] [error]: uncaughtException: create new user fail.
BadRequestError: create new user fail.
    at signUp (/home/node/app/dist/server.js:111:44704)
    at wm.handle_request (/home/node/app/dist/server.js:88:3816)
    at u (/home/node/app/dist/server.js:88:5864)
    at PM.exports.validateRegisterInput (/home/node/app/dist/server.js:114:157112)
    at wm.handle_request (/home/node/app/dist/server.js:88:3816)
    at u (/home/node/app/dist/server.js:88:5864)
    at Am.dispatch (/home/node/app/dist/server.js:88:5663)
    at wm.handle_request (/home/node/app/dist/server.js:88:3816)
    at /home/node/app/dist/server.js:88:8574
    at Kp.process_params (/home/node/app/dist/server.js:88:9118)
[3/14/2023, 1:37:27 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 1:37:50 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 1:37:51 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 1:37:51 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 1:38:01 AM] [SERVER] [info]: [object Object]
{"date":"Mon Mar 13 2023 18:38:01 GMT+0000 (Coordinated Universal Time)","error":{"name":"BadRequestError","status":400},"exception":true,"level":"error","message":"uncaughtException: create new user fail.\nBadRequestError: create new user fail.\n    at signUp (/home/node/app/dist/server.js:111:44732)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at PM.exports.validateRegisterInput (/home/node/app/dist/server.js:114:157101)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at Am.dispatch (/home/node/app/dist/server.js:88:5663)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at /home/node/app/dist/server.js:88:8574\n    at Kp.process_params (/home/node/app/dist/server.js:88:9118)","os":{"loadavg":[1.48,1.92,1.62],"uptime":2295.58},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17899025,"external":18817634,"heapTotal":28409856,"heapUsed":22462880,"rss":82968576},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"BadRequestError: create new user fail.\n    at signUp (/home/node/app/dist/server.js:111:44732)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at PM.exports.validateRegisterInput (/home/node/app/dist/server.js:114:157101)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at u (/home/node/app/dist/server.js:88:5864)\n    at Am.dispatch (/home/node/app/dist/server.js:88:5663)\n    at wm.handle_request (/home/node/app/dist/server.js:88:3816)\n    at /home/node/app/dist/server.js:88:8574\n    at Kp.process_params (/home/node/app/dist/server.js:88:9118)","trace":[{"column":44732,"file":"/home/node/app/dist/server.js","function":"signUp","line":111,"method":null,"native":false},{"column":3816,"file":"/home/node/app/dist/server.js","function":"wm.handle_request","line":88,"method":"handle_request","native":false},{"column":5864,"file":"/home/node/app/dist/server.js","function":"u","line":88,"method":null,"native":false},{"column":157101,"file":"/home/node/app/dist/server.js","function":"PM.exports.validateRegisterInput","line":114,"method":"validateRegisterInput","native":false},{"column":3816,"file":"/home/node/app/dist/server.js","function":"wm.handle_request","line":88,"method":"handle_request","native":false},{"column":5864,"file":"/home/node/app/dist/server.js","function":"u","line":88,"method":null,"native":false},{"column":5663,"file":"/home/node/app/dist/server.js","function":"Am.dispatch","line":88,"method":"dispatch","native":false},{"column":3816,"file":"/home/node/app/dist/server.js","function":"wm.handle_request","line":88,"method":"handle_request","native":false},{"column":8574,"file":"/home/node/app/dist/server.js","function":null,"line":88,"method":null,"native":false},{"column":9118,"file":"/home/node/app/dist/server.js","function":"Kp.process_params","line":88,"method":"process_params","native":false}]}
[3/14/2023, 1:38:01 AM] [SERVER] [info]: test -test -test
[3/14/2023, 1:38:01 AM] [SERVER] [error]: uncaughtException: create new user fail.
BadRequestError: create new user fail.
    at signUp (/home/node/app/dist/server.js:111:44732)
    at wm.handle_request (/home/node/app/dist/server.js:88:3816)
    at u (/home/node/app/dist/server.js:88:5864)
    at PM.exports.validateRegisterInput (/home/node/app/dist/server.js:114:157101)
    at wm.handle_request (/home/node/app/dist/server.js:88:3816)
    at u (/home/node/app/dist/server.js:88:5864)
    at Am.dispatch (/home/node/app/dist/server.js:88:5663)
    at wm.handle_request (/home/node/app/dist/server.js:88:3816)
    at /home/node/app/dist/server.js:88:8574
    at Kp.process_params (/home/node/app/dist/server.js:88:9118)
[3/14/2023, 1:45:28 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 1:46:01 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 1:46:02 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 1:46:02 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 1:46:12 AM] [SERVER] [info]: [object Object]
[3/14/2023, 1:46:12 AM] [SERVER] [info]: test -test -test
[3/14/2023, 1:46:12 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 1:46:12 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
{"date":"Mon Mar 13 2023 18:46:12 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\nError: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.cnt [as createNewUser] (/home/node/app/dist/server.js:111:44126)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:45002)","os":{"loadavg":[1.33,1.1,1.32],"uptime":2786.8},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17875108,"external":18795765,"heapTotal":22904832,"heapUsed":21387888,"rss":78159872},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }\n    at Object.cnt [as createNewUser] (/home/node/app/dist/server.js:111:44126)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signUp (/home/node/app/dist/server.js:111:45002)","trace":[{"column":44126,"file":"/home/node/app/dist/server.js","function":"Object.cnt [as createNewUser]","line":111,"method":"cnt [as createNewUser]","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":45002,"file":"/home/node/app/dist/server.js","function":"async signUp","line":111,"method":null,"native":false}]}
[3/14/2023, 1:46:12 AM] [SERVER] [error]: uncaughtException: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
Error: Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
    at Object.cnt [as createNewUser] (/home/node/app/dist/server.js:111:44126)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async signUp (/home/node/app/dist/server.js:111:45002)
[3/14/2023, 1:56:39 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 1:57:08 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 1:57:09 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 1:57:09 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 1:57:20 AM] [SERVER] [info]: [object Object]
[3/14/2023, 1:57:20 AM] [SERVER] [info]: test -test -test
[3/14/2023, 2:05:48 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 2:07:09 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 2:07:10 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 2:07:11 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 2:07:32 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:07:32 AM] [SERVER] [info]: test -test -test
[3/14/2023, 2:13:26 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 2:14:17 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 2:14:18 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 2:14:18 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 2:15:25 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:15:26 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 2:15:26 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
[3/14/2023, 2:15:26 AM] [SERVER] [error]: [App] ERROR:: "Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }"
[3/14/2023, 2:15:53 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:15:53 AM] [SERVER] [error]: Error [validation]:: ValidationError: "phone" is not allowed
[3/14/2023, 2:15:53 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"phone\" is not allowed"
[3/14/2023, 2:15:53 AM] [SERVER] [info]: err -> Error: [Validator error] :: "phone" is not allowed
[3/14/2023, 2:15:53 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:16:09 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:16:09 AM] [SERVER] [error]: Error [validation]:: ValidationError: "phone" is not allowed
[3/14/2023, 2:16:09 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"phone\" is not allowed"
[3/14/2023, 2:16:09 AM] [SERVER] [info]: err -> Error: [Validator error] :: "phone" is not allowed
[3/14/2023, 2:16:09 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:16:10 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:16:10 AM] [SERVER] [error]: Error [validation]:: ValidationError: "phone" is not allowed
[3/14/2023, 2:16:10 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"phone\" is not allowed"
[3/14/2023, 2:16:10 AM] [SERVER] [info]: err -> Error: [Validator error] :: "phone" is not allowed
[3/14/2023, 2:16:10 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:17:35 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 2:18:13 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 2:18:13 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 2:18:14 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 2:19:16 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:19:16 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 2:19:16 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
[3/14/2023, 2:19:16 AM] [SERVER] [error]: [App] ERROR:: "Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }"
[3/14/2023, 2:21:28 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:21:28 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 2:21:28 AM] [SERVER] [error]: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }
[3/14/2023, 2:21:28 AM] [SERVER] [error]: [App] ERROR:: "Error[create new user]:: E11000 duplicate key error collection: conbocudb.users index: phone_1 dup key: { phone: null }"
[3/14/2023, 2:22:50 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 2:23:20 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 2:23:21 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 2:23:21 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 2:24:10 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:24:10 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 2:25:05 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:05 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:05 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:05 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:05 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:25:09 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:09 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:09 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:09 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:09 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:25:10 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:10 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:10 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:10 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:10 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:25:10 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:10 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:10 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:10 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:10 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:25:11 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:11 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:25:11 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:11 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:25:11 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:11 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:25:11 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:25:11 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:25:11 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:31:10 AM] [SERVER] [info]: validateCreatedRole:: {"value":{"code":"ADMIN_LV_26","key":"ADMIN_LV_26","description":"","notes":""}}
[3/14/2023, 2:31:10 AM] [SERVER] [error]: [App] ERROR:: "Cannot create property 'Symbol(level)' on string 'GUEST'"
[3/14/2023, 2:33:14 AM] [SERVER] [info]: validateCreatedRole:: {"value":{"code":"ADMIN_LV_27","key":"ADMIN_LV_27","description":"","notes":""}}
[3/14/2023, 2:33:14 AM] [SERVER] [error]: [App] ERROR:: "Cannot create property 'Symbol(level)' on string 'GUEST'"
[3/14/2023, 2:36:44 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 2:38:34 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 2:38:35 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 2:38:35 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
[3/14/2023, 2:38:46 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:38:46 AM] [SERVER] [error]: Error [validation]:: ValidationError: "repeat_password" must be [ref:password]
[3/14/2023, 2:38:46 AM] [SERVER] [error]: [App] ERROR:: "[Validator error] :: \"repeat_password\" must be [ref:password]"
[3/14/2023, 2:38:46 AM] [SERVER] [info]: err -> Error: [Validator error] :: "repeat_password" must be [ref:password]
[3/14/2023, 2:38:46 AM] [SERVER] [info]: BadRequestError
[3/14/2023, 2:38:52 AM] [SERVER] [info]: [object Object]
[3/14/2023, 2:38:52 AM] [SERVER] [info]: Kon Testing::
[3/14/2023, 2:40:14 AM] [SERVER] [info]: validateCreatedRole:: {"value":{"code":"ADMIN_LV_27","key":"ADMIN_LV_27","description":"","notes":""}}
[3/14/2023, 2:40:14 AM] [SERVER] [info]: GUEST
[3/14/2023, 2:40:14 AM] [SERVER] [error]: [VERIFY_TOKEN]:: jwt expired
[3/14/2023, 2:40:14 AM] [SERVER] [error]: [App] ERROR:: "Token failed or expired"
[3/14/2023, 2:40:14 AM] [SERVER] [info]: err -> Error: Token failed or expired
[3/14/2023, 2:41:23 AM] [SERVER] [info]: validateCreatedRole:: {"value":{"code":"GUEST","key":"GUEST","description":"GUEST","notes":"GUEST"}}
[3/14/2023, 2:41:23 AM] [SERVER] [info]: GUEST
[3/14/2023, 2:41:23 AM] [SERVER] [error]: uncaughtException: i.roles is not iterable
TypeError: i.roles is not iterable
    at checkRole (/home/node/app/dist/server.js:114:161308)
{"date":"Mon Mar 13 2023 19:41:23 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: i.roles is not iterable\nTypeError: i.roles is not iterable\n    at checkRole (/home/node/app/dist/server.js:114:161308)","os":{"loadavg":[1.09,1.54,1.42],"uptime":6097.25},"process":{"argv":["/usr/local/bin/node","/home/node/app/dist/server.js"],"cwd":"/home/node/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17932539,"external":18851113,"heapTotal":22372352,"heapUsed":20653552,"rss":77496320},"pid":1,"uid":1000,"version":"v18.15.0"},"stack":"TypeError: i.roles is not iterable\n    at checkRole (/home/node/app/dist/server.js:114:161308)","trace":[{"column":161308,"file":"/home/node/app/dist/server.js","function":"checkRole","line":114,"method":null,"native":false}]}
[3/14/2023, 2:45:21 AM] [DATABASE] [info]: Mongoose 'default' connection disconnected
[3/14/2023, 2:46:49 AM] [SERVER] [info]: Starting server with port:: 9000
[3/14/2023, 2:46:50 AM] [DATABASE] [info]: MongoDb:: [konking] is connected!
[3/14/2023, 2:46:50 AM] [DATABASE] [info]: MongoDb:: [conbocudb] is connected!
